export const aboutData = {
  id: 'about',
  topLine: 'ABOUT ME',
  headline: '끊임없이 궁금해하고 습득하는 과정에서 즐거움을 느끼며, 어제보다 더 나은 개발자가 되겠습니다.',
  description1: '2019.02 인천대학교 전자공학과 졸업 (학사)',
  description2: '2020.02 - 12 Dell International Inc. (Technical support, 사원)',
  description3: '2021.02 - 06 웹개발자 과정 수료',
  img: require('../../images/profile.webp').default,
  alt: 'profile',
  html: require('../../images/skills/html.png').default,
  css: require('../../images/skills/css.png').default,
  jquery: require('../../images/skills/jquery.webp').default,
  js: require('../../images/skills/js2.png').default,
  node: require('../../images/skills/node.png').default,
  react: require('../../images/skills/react.png').default,
  sass: require('../../images/skills/sass.webp').default,
  maria: require('../../images/skills/mariadb1.png').default,
  mongo: require('../../images/skills/mongodb1.webp').default,
  name: "김민지",
  ename: "MinJi Kim"
}
